server:
  servlet:
    # Response UTF-8 Encoding 설정
    encoding:
      charset: UTF-8
      force: true

db:
  datasource:
    # primary datasource info
    primaryurl: jdbc:log4jdbc:mariadb://swontech-webservice-database.cee5fuoc2j3u.ap-northeast-2.rds.amazonaws.com:3306/tb_s020
    primaryusername: swontech
    primarypassword: Car583242~
    primarydriver: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

redis:
  host: localhost
  port: 6379

jwt:
  secretkey: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health, beans
